### ISSUE TITLE
Github readme is missing Ch340 driver installtion step.

### ISSUE THREAD

**Issue by Zero-Circle** [prusa3d/Prusa-Firmware-ESP32-Cam#11]
Same as the title, the github installation steps is missing the CH340 driver installation step for windows.

**Comment by johnyHV** [comment]
The manual for installing the driver is in the blog post

https://blog.prusa3d.com/development-of-the-open-source-camera-firmware-solution-from-the-community-for-prusa-printers_94421/

direct link is here 

https://storage.googleapis.com/prusa3d-content-prod-14e8-wordpress-blog-prod/2024/03/4268e263-gen_prusa-connect-prusalink_1636_en_2024-04-25-2.pdf
