### ISSUE TITLE
Prusa Connect Camera name resets after Camera reboot

### ISSUE THREAD

**Issue by jimwsmith** [prusa3d/Prusa-Firmware-ESP32-Cam#19]
Every time Camera reboots, the displayed name in PrusaConnect resets to ESP32-CAM.
I manually edit it and it's fine until the camera reboots

**Comment by jimwsmith** [comment]
Would be great to have ability to set Camera name in ESP32-cam.

**Comment by johnyHV** [comment]
@jimwsmith The current FW 1.0.2-rc2 uses the mDNS record as the camera name in PrusaConnect. I think it is the correct use of one variable for 2 functions.

**Comment by jimwsmith** [comment]
> @jimwsmith The current FW 1.0.2-rc2 uses the mDNS record as the camera name in PrusaConnect. I think it is the correct use of one variable for 2 functions.

Works great (and saves creating a new setting too)

**Comment by johnyHV** [comment]
Great. Thank you for the improvement suggestion :) .
