### ISSUE TITLE
Weird Wi-Fi configuration after update from 1.01 to 1.02-rc1

### ISSUE THREAD

**Issue by MarkusReichart** [prusa3d/Prusa-Firmware-ESP32-Cam#26]
Maybe I missed the notice to reset/flash the board. After the cloud update, the camera connects to wifi but in the Wifi section "Connection Status" is empty an the button "Advanced Wi-Fi settings" is missing.

**Comment by yasars** [comment]
same problem...

**Comment by johnyHV** [comment]
it is necessary to clear the cache in the browser

**Comment by MarkusReichart** [comment]
yes, clearing the browser cache solved this issue for me.

**Comment by johnyHV** [comment]
I forgot to include this information in the release notes... I already fixed it....
