### ISSUE TITLE
Unique title for browser tab

### ISSUE THREAD

**Issue by MarkusReichart** [prusa3d/Prusa-Firmware-ESP32-Cam#37]
I run more than one camera and want to bookmark them in my browser. The **Title-Tag** of the HTML code seems to be always _Prusa ESP32-cam_ . Setting the HTML title to mDNS record seems as easy option for me.

**Comment by johnyHV** [comment]
Hello @MarkusReichart. This functionality are added in the Firmware version 1.0.3-rc2 :)
