### ISSUE TITLE
ESP32 flash Hz bar artefacts

### ISSUE THREAD

**Issue by Simon7381** [prusa3d/Prusa-Firmware-ESP32-Cam#38]
There seems to be a Hz interference with the LED used for the flash.
Please note, I have rotated the image 270d, so these are horizontal banding lines with the print bed to the right and extruder at the bottom.

- With the LED off and illuminated by room LED lights:
- - ![Room-LED-saved-photo](https://github.com/prusa3d/Prusa-Firmware-ESP32-Cam/assets/16381321/085611a2-cfd4-49fe-a2b8-669525b63e78)
- With the LED on constantly and illuminated by room LED lights:
- - ![Const-Flash-Room-LED-saved-photo](https://github.com/prusa3d/Prusa-Firmware-ESP32-Cam/assets/16381321/a33c2968-4071-4d34-b2bd-7e7bdff6955f)
- With the LED on flash and illuminated by room LED lights:
- - ![snapshot-prusa-esp32cam-1717283151](https://github.com/prusa3d/Prusa-Firmware-ESP32-Cam/assets/16381321/c7cbf21c-2e64-4500-ac4e-2c2ce4ec17f2)
- With the LED on flash:
- - ![snapshot-prusa-esp32cam-1717283244](https://github.com/prusa3d/Prusa-Firmware-ESP32-Cam/assets/16381321/68f7f171-9961-4347-b19f-8609052bff1f)
- With the LED on flash, battery USB:
- - ![snapshot-prusa-esp32cam-1717284731](https://github.com/prusa3d/Prusa-Firmware-ESP32-Cam/assets/16381321/3c934468-b779-4b78-b5ef-821425fb13cc)
- Original Prusa Enclosure LED strip:
- - ![snapshot-prusa-esp32cam-1717285009](https://github.com/prusa3d/Prusa-Firmware-ESP32-Cam/assets/16381321/9a087e37-f22c-4e7a-bb58-dd5a48e016d0)

I'm in the UK with 50Hz electricity, with ESP32 from https://amzn.eu/d/54PickP
I've tried different USB power supplies, including a battery to eliminate the 50Hz mains frequency.

I guess this is the LED on the board, but is it I've got a bad board or is this some LED driver pulsing the flash, is there any setting that can be done to eliminate or tune out this interference banding?

**Comment by johnyHV** [comment]
Hello @Simon7381. I am in the EU and also have 50Hz electricity. I haven't seen this problem yet. Currently, you need to manually change the setting in the code, in the mcu_cfg.h file, and variable

`
#define FLASH_ON_STATUS   205   ///< PWM intensity LED for ON. limitation to 80%. 2^FLASH_PWM_RESOLUTION * 0.8% = 204
#define FLASH_PWM_FREQ   2000               ///< frequency of pwm [240MHz / (100 prescale * pwm cycles)] = frequency
`

In the future I can added new parameter on the WEB page, for settings PWM intensity. Can you test change at first step FLASH_ON_STATUS    ?

**Comment by Simon7381** [comment]
> Hello @Simon7381. I am in the EU and also have 50Hz electricity. I haven't seen this problem yet. Currently, you need to manually change the setting in the code, in the mcu_cfg.h file, and variable
> 
> 
> 
> `
> 
> #define FLASH_ON_STATUS   205   ///< PWM intensity LED for ON. limitation to 80%. 2^FLASH_PWM_RESOLUTION * 0.8% = 204
> 
> #define FLASH_PWM_FREQ   2000               ///< frequency of pwm [240MHz / (100 prescale * pwm cycles)] = frequency
> 
> `
> 
> 
> 
> In the future I can added new parameter on the WEB page, for settings PWM intensity. Can you test change at first step FLASH_ON_STATUS    ? 

I had been lazzy and used the binnary to upload, so will give me an excuse to get the arduino setup on Monday 😀
Will let you know, thanks

**Comment by johnyHV** [comment]
Hi @Simon7381 . LED diode on the PCB don't have resistor for the current limitation. So currently is for testing changed PWM to 80%. Maybe this "solution" should be help extend LED diode life time. Can you try use original PWM frequency, and 100% PWM ?
