### ISSUE TITLE
Image Rotation not applied to stream.mjpg

### ISSUE THREAD

**Issue by ice987987** [prusa3d/Prusa-Firmware-ESP32-Cam#39]
the new `image rotation` feature, implemented with `1.0.3-rc2`, is not applied to the stream `http://[ip]/stream.mjpg`.

**Comment by johnyHV** [comment]
@ice987987 Yes, the stream currently does not support EXIF metadata. I will try to implemented it in the next version of the firmware. For now, I don't know if it will be possible to use EXIF metadata with the stream. EXIF metadata must be calculated for each image individually. Adding EXIF metadata may cause higher CPU load and may reduce the number of FPS. These are just estimates, and I need to test it.

**Comment by twjdeboer** [comment]
Visual indication of the problem: The small thumbnails do not rotate according to the setting, but the camera view does.

![Screenshot 2024-06-10 160141](https://github.com/prusa3d/Prusa-Firmware-ESP32-Cam/assets/9251213/523ecfdd-e5ff-4343-99f8-18e5d196fcbc)

**Comment by johnyHV** [comment]
@ice987987 Experimentally, I added EXIF for the stream, but so far I am not satisfied with the board's performance. By default, EXIF for the stream is turned off. However, you can enable it by using the macro **CAMERA_EXIF_ROTATION_STREAM** in **mcu_cfg.h**.

**Comment by ice987987** [comment]
thank you very much!
