### ISSUE TITLE
URL for control Light

### ISSUE THREAD

**Issue by Flavien06** [prusa3d/Prusa-Firmware-ESP32-Cam#41]
Hi
Would it be possible to add a simple URL request,
for example, http://prusa-esp32cam.local/light?on and http://prusa-esp32cam.local/light?off
to control the LED from a home automation application (to activate it automatically at night, for example)?

Same option for refreach snapshot  
http://prusa-esp32cam.local/snapshot
(to make a New snapshot for send with notification) 

Thank

**Comment by blurfl** [comment]
This approach makes more sense than a control through PrusaConnect or PrusaLink.

**Comment by johnyHV** [comment]
Hello @Flavien06 . This is good idea. I can added requests

**Comment by johnyHV** [comment]
Hello @Flavien06 WEB API is already added [here](https://github.com/prusa3d/Prusa-Firmware-ESP32-Cam?tab=readme-ov-file#web-api)

**Comment by Flavien06** [comment]
OK nice. I juste udate to v1.1.0-rc1

All commande works exept light and flash

For http://ip/light?on 
```
URL not Found

URI: /light
Method: GET
Arguments: 1
 on: 
```

**Comment by johnyHV** [comment]
@Flavien06 for me it works. Please, can you try it again ? 

![image](https://github.com/prusa3d/Prusa-Firmware-ESP32-Cam/assets/4459753/497b95c1-6cff-46cb-a63a-616bee625994)

**Comment by Flavien06** [comment]
I tried but still url not found. I'll try to reflash the firmware later.

**Comment by Flavien06** [comment]
It's good after new flashing of firmware it works.

_Thanks :) I added the functions to my script
https://github.com/Flavien06/PrusaLinkAPI-SH

**Comment by Flavien06** [comment]
It's good after new flashing of firmware it works.

_Thanks :) I added the functions to my script
https://github.com/Flavien06/PrusaLinkAPI-SH_
