### ISSUE TITLE
ESP32-CAM not showing up in Device Manager win 11

### ISSUE THREAD

**Issue by rmilyard** [prusa3d/Prusa-Firmware-ESP32-Cam#43]
When I plug in my ESP32-CAM Ver 1 (I believe) it isn't showing up in Device Manager for WIn 11.  What could be my issue?

**Comment by johnyHV** [comment]
This is problem with driver for CH340 (USB to UART converter). For example here is one [driver version](https://www.wch-ic.com/search?q=CH340&t=downloads) and here is older [driver version](https://blog.laskakit.cz/wp-content/uploads/2020/03/CH341SER.zip)
