### ISSUE TITLE
Incorrectly labeled pin for LED relay

### ISSUE THREAD

**Issue by Zero-Circle** [prusa3d/Prusa-Firmware-ESP32-Cam#48]
I started diagnosing why my relay wasnt firing when turning the flash on and off and discovered that the relay schematic in [this section](https://github.com/prusa3d/Prusa-Firmware-ESP32-Cam?tab=readme-ov-file#flash-led-issue) is incorrect.

On the ESP32cam schmatic it is labelled as HS2_Data_1, in the above diagram it says to connect it to HS2_CLK.
![image](https://github.com/prusa3d/Prusa-Firmware-ESP32-Cam/assets/111734887/e90d0e0a-2bcf-4330-86ee-b89fba31d684)
![image](https://github.com/prusa3d/Prusa-Firmware-ESP32-Cam/assets/111734887/676047a7-f9cc-4d0f-9622-f1cfd4ba2d65)

The diagram needs to be updated to look like this(green line indicates new route):
![image](https://github.com/prusa3d/Prusa-Firmware-ESP32-Cam/assets/111734887/2481e6e1-479d-4e9f-bc04-3f0d1f5e5b71)

If I've somehow missed something here please let me know. 
This is a working config on my all my boards so I dont think I have a dud board or different board revision.

**Comment by johnyHV** [comment]
@Zero-Circle thanks i'll check it out

**Comment by johnyHV** [comment]
@Zero-Circle yes, you have right. Thank you for the correction
