### ISSUE TITLE
no wifi with 1.0.1

### ISSUE THREAD

**Issue by yasars** [prusa3d/Prusa-Firmware-ESP32-Cam#5]
in 1.0 wifi ist working... after update i have no wifi connection only wifi hotspot with 192.168.0.1 is working but no internet :(

go back to 1.0

and pls update the readme ank link to prusa esp32 cam i mean your old project https://github.com/johnyHV/PrusaConnect_ESP32-CAM

**Comment by johnyHV** [comment]
Thank you for the report.

In FW version 1.0.1, the camera did not see any WiFi networks, or just did not connect to the WiFi network? Please can you send me the logs from the camera for FW 1.0.1 ? You can find the logs on the system page, but you need to have a micro SD card inserted.

**Comment by yasars** [comment]
I deleted everything, played fw on it, entered wifi... but after a restart it doesn't connect to the wifi... don't have time for that at the moment, if you put out a new fw and the bug is still there then you'll get it my logs...

**Comment by yasars** [comment]
and when I compile it under Arduino, the WiFi server doesn't run either.... the password for connecting the hotspot 12345678 doesn't match...the above happens with your finished image

**Comment by Fluffybunny96** [comment]
I have the same issue, how can I provide the logs to help with this ?

**Comment by johnyHV** [comment]
Sorry @yasars , but I can't analyze the problem without logs

**Comment by johnyHV** [comment]
@Zero-Circle , maybe you have a problem with the driver on the first computer. [here](https://blog.laskakit.cz/wp-content/uploads/2020/03/CH341SER.zip) is the older driver version for CH340.
