### ISSUE TITLE
ESP Cam overheating

### ISSUE THREAD

**Issue by hollandm** [prusa3d/Prusa-Firmware-ESP32-Cam#50]
While running this on an ESP cam with basically stock settings my esp-cam board is hot to the touch and the software is reporting that it is 80C and still gradually rising. I've got 5v going into the 5v pin and a ground connection from a USB and no other connected wires.

Is this normal or do I have a bad board?

**Comment by mozgy** [comment]
ESP32 S is not supported for reading internal temp per espressif doc. Internal HW does exists but it is unreliable so it is 'normal'.

**Comment by johnyHV** [comment]
@hollandm yes, this temperature is normal
