### ISSUE TITLE
HELP.... FOV and focus

### ISSUE THREAD

**Issue by donmaro** [prusa3d/Prusa-Firmware-ESP32-Cam#52]
Hi, Currently this is my image quality:

![image](https://github.com/user-attachments/assets/584b717c-44ad-49b9-8cf8-881485a7ff44)

This is not that great. how can i adjust the FOV and and the focus to get better quality?

Thanks in advance.

**Comment by mikromcz** [comment]
It looks out of the focus. You can twist the lense a bit clockwise or counterclockwise to get the best results. You can print a small wrench like this https://www.printables.com/model/700239-esp32-cam-ov2640-focus-adjustment-wrench-tool or just use pliers 😏

**Comment by donmaro** [comment]
hmmm got it in focus but now it is really zoomed in somehow....

![image](https://github.com/user-attachments/assets/8ff7481d-540a-4cac-8ad0-6263164e5ef8)

I would like a more zoomed out view

**Comment by johnyHV** [comment]
Hello @donmaro camera don't have support for the automatically focus. Here is simple manual with tool for the focus

https://github.com/prusa3d/Prusa-Firmware-ESP32-Cam?tab=readme-ov-file#man_focus

Unfortunately, you have to focus the camera manually
