### ISSUE TITLE
Camera does not store the values changed in the UI

### ISSUE THREAD

**Issue by Mr3Deee** [prusa3d/Prusa-Firmware-ESP32-Cam#57]
Many thanks for all the effort which is going into this project!

I have various parameters which I have always turn on by hand:
1. LED keep on (so that the photos are not black)
2. Set tha auto gain to anything but 0 (to make it brighter)
3. ..

However - as soon as you restart the page and / or the camera all is going back to the previous state.
I have seen that this worked previously with the old / other apps I have tried on the module.

**Comment by johnyHV** [comment]
Hello @Mr3Deee . Configuration saving still works. Keeping the LED on for a long time is not a good idea. The LED can overheat and permanently damage the module. There is a flash function available as an option. The software automatically turns on the LED for a short interval before taking a picture

![image](https://github.com/user-attachments/assets/1567c062-9271-4422-983f-60a1a915aed8)
