### ISSUE TITLE
File names typo in Mac/Linux flash commands 

### ISSUE THREAD

**Issue by ericd1949** [prusa3d/Prusa-Firmware-ESP32-Cam#6]
Fantastic work! This is great fun - thank you.

The bin files names in the Mac/Linux flash commands do not match the download asset files, presumably you changed the bin file names at some point. And, there are 3 embedded c/r's, so if you cut and paste the command into the Mac terminal console, it sees 4 separate commands.

I had a couple of the type 2 ESP32-CAM boards and used a FTDI programmer. I copied your bin files and the esptool into one folder, gave the esptool execute permissions, and used this command:

./esptool -p /dev/tty.usbserial-A600CDG1 -b 460800 --before default_reset --after hard_reset --chip esp32 write_flash --erase-all --flash_mode dio --flash_size 4MB --flash_freq 80m 0x1000 ./ESP32_PrusaConnectCam.ino.bootloader.bin 0x8000 ./ESP32_PrusaConnectCam.ino.partitions.bin 0x10000 ./ESP32_PrusaConnectCam.ino.bin

Not sure if all the "./" are needed, but it worked for me. The "python3 -m" didn't work for me, it gave a "No module named esptool" error message. So I used the esptool command directly as above. Somewhere in my wanderings I think I found that's how Esprissif say to do it - can't find that reference now :-(

Thanks again.
( I'm using a Mac Mini macOS Sonoma 14.4.1)

**Comment by johnyHV** [comment]
Thanks for correcting the command. Yes, the name of the project was changed and there were white characters. I updated it in the documentation

Thanks
