### ISSUE TITLE
How do you change the mcu_cfg.h File?

### ISSUE THREAD

**Issue by thni1703** [prusa3d/Prusa-Firmware-ESP32-Cam#63]
I have googled everything I can think of.
It is just a footnote, but have cost me a lot of time :(
It is probably something simle, but I do not see it.

**Comment by johnyHV** [comment]
Hello @thni1703 . Why do you need change the mcu_cfg.h file ? After modifying the mcu_cfg.h file, you need to compile your own firmware and upload it to the MCU. You can still use the official firmware, which you can find in the release page https://github.com/prusa3d/Prusa-Firmware-ESP32-Cam/releases

**Comment by thni1703** [comment]
Hi, it says so in the guides? Set True to the MCU you are using and False to the others?

![grafik](https://github.com/user-attachments/assets/53552d5d-81e2-48d2-a537-f4467d769159)

**Comment by johnyHV** [comment]
@thni1703 Yes, this is just for compilation new FW
