### ISSUE TITLE
unable erase/flash memory

### ISSUE THREAD

**Issue by 8Sam6AcidP** [prusa3d/Prusa-Firmware-ESP32-Cam#69]
Hello 
I would like to set up an ESP32-S3-EYE using the Prusa instructions 
(https://help.prusa3d.com/guide/esp-camera-for-prusa-connect_390199)

However, I am unable to delete the memory (step 11). Nothing happens after pressing the Erase button. The following message appears in the window next to it.   

![IMG_7858](https://github.com/user-attachments/assets/573a9db7-7554-4dd7-b753-2d0cabb66fc3)

I have now gone through the instructions several times and have followed the instructions. 

Does anyone know any advice? Does anyone have the same problem?   

Thank you very much and best regards 
SaM 

Kamera ESP32-S3-EYE 
Firmware 1.1.0
Flash download tools 3.9.7
Windows 10

**Comment by johnyHV** [comment]
Hello @8Sam6AcidP did you switch the board to bootloader mode before pressing ERASE?

![image](https://github.com/user-attachments/assets/3a750fc1-3052-4e31-9cd8-4964ae4af819)

**Comment by 8Sam6AcidP** [comment]
Thank you for your support. 
Yes, i switch the board to bootloader mode. 

I tried again with the OSX manual on github and changed a few commands as suggested in the comments on the Prusa site. Now the camera works. However, I don't know what the mistake was.
