### ISSUE TITLE
cam doesn't register with Prusa

### ISSUE THREAD

**Issue by rbronco21** [prusa3d/Prusa-Firmware-ESP32-Cam#7]
I've entered the token and it sat overnight and the Prusa site says it hasn't registered. My first cam had poor picture quality (back to Amazon!), but seemed to register immediately.

I can't see logs because I don't have an sd card inserted. "Micro SD card not found with FAT32 partition!" Is this a requirement for logs, or is it an issue?

**Comment by johnyHV** [comment]
Thank you for the report.

Please, did you check whether the token did not have a white character inserted? For example, a space character ?

Yes, for the log is necessary inserted micro SD card formatted to FAT32. It will help me a lot if you send me the log file from the camera.

**Comment by johnyHV** [comment]
Apparently the problem has been solved. closes the ticket. If the problem occurs again, please open the ticket again
