### ISSUE TITLE
Where to buy in Europe?

### ISSUE THREAD

**Issue by bodokaiser** [prusa3d/Prusa-Firmware-ESP32-Cam#79]
Hi all,

thanks for sharing and extending this beautiful project!

For the last days, I have been searching the internet for a distributor where I can buy any of the supported camera modules. However, I have failed to find the exact same version in stock and deliverable to the EU (Germany). I have tried Amazon, Conrad, Reichelt, RS-components, Mouser, and Digikey.

It would be great to add links of potential distributors to the supported boards section in the README.md or at least share some links unofficially in this thread.

**Comment by mozgy** [comment]
Mouser sends all it's 'stuff' from Italy warehouse.

**Comment by bodokaiser** [comment]
Thank you!

> https://www.az-delivery.de/en/products/esp32-cam-modul-esp32-wifi-bluetooth-modul-inklusive-kamera

Which firmware would I have to use for this one?

**Comment by Maintraxx** [comment]
You also find it on amazon with USB Port, which is very helpful: https://www.amazon.de/gp/product/B0D9BSRYF9

Then you can install the firmware online with a browser: https://ald-models.github.io/Prusa-ESP32-Cam-Web-Upload/
